### ISSUE TITLE
Surrogate key generation fails for `BYTES` columns in BigQuery

### ISSUE THREAD

**Issue by prakharb10** [dbt-labs/dbt-utils#1023]
### Describe the bug

The `generate_surrogate_key` macro fails if one of the primary keys columns specified is of the `BYTES` data type.

### Steps to reproduce

In a model select statement:
`{{ dbt_utils.generate_surrogate_key(['col1', 'col2']) }} as key`

### Expected results

The macro should cast the `BYTES` columns appropriately to `STRING`.

### Actual results

Model fails to build

### Screenshots and log output

```
Database Error in model _sapsll_legtpr_pt3_sapsr3_current (models/raw/oracle_pt3_sapsr3_lake/_sapsll_legtpr_pt3_sapsr3_current_v1.sql)
  Invalid cast of bytes to UTF8 string
```

### System information
**The contents of your `packages.yml` file:**
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - package: metaplane/dbt_expectations
    version: 0.10.8
  - package: dbt-labs/codegen
    version: 0.13.1
  - package: dbt-labs/audit_helper
    version: 0.12.1
  - package: dbt-labs/dbt_project_evaluator
    version: 1.0.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
Run on dbt cloud so, `latest`.

### Additional context

Looks like either [`TO_BASE64`](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#to_base64) or [`SAFE_CONVERT_BYTES_TO_STRING`](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#safe_convert_bytes_to_string) could do the job. The SQL generated right now is a simple `CAST`.

### Are you interested in contributing the fix?

I'm open to it, with some direction. Since this is (maybe) BigQuery specific, would a fix go into the adapter specific implementation of this macro?
