### ISSUE TITLE
Columns names that must quoted are confusing in YAML

### ISSUE THREAD

**Issue by dah33** [dbt-labs/dbt-utils#389]
### Describe the bug

Column names that must be quoted, e.g. spaces, aren't well supported in YAML:

```
sources:

  - name: dbt_is_nearly_perfect
    loaded_at_field: '"Data Load Date/Time"' <--- MUST BE SINGLE AND DOUBLE QUOTED
    freshness:
      error_after: {count: 1, period: day}
```

Instead of the intuitive:

```
sources:

  - name: dbt_is_perfect
    loaded_at_field: Data Load Date/Time
    freshness:
      error_after: {count: 1, period: day}
```

### System information

I have dbt_utils 0.6.6 and dbt cloud IDE

**Which database are you using dbt with?**

postgres
