### ISSUE TITLE
dbt_utils.get_column_values should use the Relation object it's given instead of making its own

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [dbt-labs/dbt-utils#424]
### Describe the bug

The `get_column_values` and `star` macros do not seem to properly work when the source is passed through as an argument and the `src.yml` is leveraging the non-default [quoting](https://docs.getdbt.com/reference/project-configs/quoting). Specifically for Snowflake.

### Steps to reproduce

Use [quoting](https://docs.getdbt.com/reference/project-configs/quoting) in your `src.yml`:
```yml
version: 2

sources:
  - name: salesforce
    schema: 'salesforce'
    database: mydatabase
    quoting: 
          database: false
          schema: true
          identifier: true

    tables:
      - name: fivetran_formula
      - name: test_order_c
```
With the above `src.yml` config if I attempt to use the `get_column_values` and `star` macro like below:
```sql
{%- set old_formula_fields = dbt_utils.get_column_values(source('salesforce', 'fivetran_formula'),'field') | upper -%}

select
{{ dbt_utils.star(source('salesforce','test_order_c'), except=old_formula_fields) }}
from {{ source('salesforce', 'test_order_c') }}
```
The resulting compiled output is completely empty.
```sql
select

from DATABASE."SCHEMA"."test_order_c"
```

### Expected results

If I remove the quoting config in the `src.yml` then I see the output as expected. The expected results would be to allow users that have to use the quoting config to still be able to use the combination of these macros.
```sql
select
    "FIELDS_I_WANT",
    "ETC"
from DATABASE."SCHEMA"."test_order_c"
```

### Actual results

Compiled output below.
```sql
select

from DATABASE."SCHEMA"."test_order_c"
```

### System information
**The contents of your `packages.yml` file:**
```yml
packages:
  - package: fivetran/salesforce_formula_utils
    version: [">=0.4.0", "<0.5.0"]
  - package: fivetran/fivetran_utils
    version: [">=0.2.0", "<0.3.0"]
  - package: dbt-labs/dbt_utils
    version: [">=0.7.0", "<0.8.0"]
```
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.2
   latest version: 0.20.2

Up to date!

Plugins:
  - bigquery: 0.20.2
  - snowflake: 0.20.2
  - redshift: 0.20.2
  - postgres: 0.20.2
  - spark: 0.20.2
```

### Are you interested in contributing the fix?

I would be happy to contribute to this fix! However, I am not entirely sure where the issue is arising? Once we locate, I would be happy to help in any way I can!
