### ISSUE TITLE
default__get_relations_by_pattern fails due to agate.row value selection by column name

### ISSUE THREAD

**Issue by TerjeRusska** [dbt-labs/dbt-utils#484]
### Describe the bug
`default__get_relations_by_pattern` is failing due to agate.row column selection by name being case sensitive. The relation creation process does not receive row values.

### Steps to reproduce
`{{ dbt_utils.get_relations_by_pattern('%', '%', '', 'RAW') }}`

### Expected results
List of snowflake relations in the target sql file

### Actual results
```
Runtime Error
  Field "path" of type Path in SnowflakeRelation has invalid value {'database': 'RAW', 'schema': Undefined, 'identifier': Undefined}
```

### Screenshots and log output
In `default__get_relations_by_pattern`

`{% do log(table_list['table'], info=True) %}`

| column       | data_type |
| ------------ | --------- |
| TABLE_SCHEMA | Text      |
| TABLE_NAME   | Text      |
| TABLE_TYPE   | Text      |

agate.row value selection with `row.table_schema` will not give any results, however it does work it `row.TABLE_SCHEMA`

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0", "<0.9.0"]
  - package: brooklyn-data/dbt_artifacts
    version: [">=0.6.0", "<0.7.0"]
  - package: dbt-labs/codegen
    version: [">=0.5.0", "<0.6.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 1.0.1
   latest version: 1.0.1

Up to date!

Plugins:
  - snowflake: 1.0.0
```

### Are you interested in contributing the fix?
I can work on a fix that covers both lower and uppercase column names.
