### ISSUE TITLE
Bug? fivetran/fivetran_utils

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-utils#499]
### Discussed in https://github.com/dbt-labs/dbt-utils/discussions/493

<div type='discussions-op-text'>

<sup>Originally posted by **shakermakerk** February 11, 2022</sup>
Hey guys,

When I try and install this package via packages.yml I get an error, can anyone help or confirm if it is an ongoing bug?

```
 package: fivetran/tiktok_ads
 version: 0.1.1
```

I get this error message: 

```
Encountered an error:
Version error for package fivetran/fivetran_utils: Could not find a satisfactory version from options: ['=0.2.9', '>=0.2.0', '<0.3.0', '>=0.2.0', '<0.3.0', '>=0.2.0', '<0.3.0', '>=0.3.0', '<0.4.0'] 
```

this is my full packages file 

```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.3

  - package: fivetran/fivetran_utils
    version: 0.2.9

  - package: fivetran/tiktok_ads
    version: 0.1.1

  - package: fivetran/stripe_source
    version: 0.4.3

  - package: fivetran/pinterest_source
    version: 0.4.0

  - package: fivetran/microsoft_ads_source
    version: 0.3.1
```

this is my dbt version info
```
installed version: 0.21.1
   latest version: 1.0.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.21.1
  - snowflake: 0.21.1
  - redshift: 0.21.1
  - postgres: 0.21.1
(condaEnv) chriswood@ChrissKKomputer bla-data % 
```
</div>

**Comment by joellabes** [comment]
hi @shakermakerk, I moved this from a discussion to an issue on your behalf. A couple of comments:

- I wouldn’t directly import fivetran_utils - it will be brought into your packages automatically based on the other dependencies you have defined.
- Your dbt project is 0.21.1, but the tiktok ads project requires dbt Core 1.0.0 or greater. By upgrading dbt Core to v1, and changing your other packages to the 1.0-compatible versions, you will be able to make everything work together:
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0","<0.9.0"]

  - package: fivetran/tiktok_ads
    version: [">=0.1.0","<0.2.0"]

  - package: fivetran/stripe_source
    version: [">=0.5.0","<0.6.0"]

  - package: fivetran/pinterest_source
    version: [">=0.5.0","<0.6.0"]

  - package: fivetran/microsoft_ads_source
    version: [">=0.4.0", "<0.5.0"]
 ```
 
Note that I've removed the reference to fivetran_utils, bumped the other packages' versions to the latest 1.0 compatible ones, and changed them to minor version ranges (e.g. 0.5.x for stripe). By depending on a range, you give the package manager more flexibility to identify cross-compatible versions.

I'm going to close this out, but let me know if you have any followup questions. 

If you're not able to upgrade to dbt Core 1.0 yet, you'll need to remove your dependency on the tiktok package.
