### ISSUE TITLE
Tests don't run for deduplicate macro

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-utils#579]
### Describe the bug
This is one instance within #558

The `deduplicate` macro is untested because this code refers to `test_dedupe` rather than `test_deduplicate`:
```yaml
  - name: test_dedupe
    tests:
      - dbt_utils.equality:
          compare_model: ref('data_deduplicate_expected')
```

### Steps to reproduce
```shell
cd integration_tests
dbt build --select +test_dedupe
```
or
```shell
cd integration_tests
dbt build --select +test_deduplicate
```

### Expected results
The relevant test would run.

### Actual results
Neither example runs the relevant test.

For the first example, it gives this warning:
```
01:40:33  [WARNING]: Test 'test.dbt_utils_integration_tests.dbt_utils_equality_test_dedupe_ref_data_deduplicate_expected_.2275e15126' (models/sql/schema.yml) depends on a node named 'test_dedupe' which was not found
```

### Are you interested in contributing the fix?
I'm your huckleberry.
