### ISSUE TITLE
Macro deleted in `0.9.3`

### ISSUE THREAD

**Issue by courentin** [dbt-labs/dbt-utils#716]
### Describe the bug
Updating to >= `0.9.3` remove macros that were deprecated.
Is `dbt_utils` not using semantic versioning?

### Steps to reproduce
Install dbt_utils `0.9.4` for example, call `dbt_utils.current_timestamp_in_utc()`, it will fail.

### Expected results
I am not expecting a bug release of this package to have breaking changes. We pinned `dbt_utils` to a minor version to ensure we have all the bug fixes.
Why these macros were not removed in a `1.0.0` version?

### Actual results
Deprecated macros have been deleted.

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.9.2", "<0.10.0"]
  - package: calogica/dbt_expectations
    version: [">=0.6.0", "<0.7.0"]
```
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)
