### ISSUE TITLE
dateadd deprecation warning triggered when dateadd is used within date_spine

### ISSUE THREAD

**Issue by LoicChesneau** [dbt-labs/dbt-utils#722]
### Describe the bug

Warning seems to be raised mistakenly because a deprecated dbt_utils feature is called within a valid dbt_utils function.

### Steps to reproduce

Run the following as a model (in this example, the name of the model is `snowflake_amortized_rates` 
```
{{ 
	dbt_utils.date_spine(
		start_date = "to_date('11/01/2009', 'mm/dd/yyyy')",
		datepart = "day",
		end_date = "dateadd(year, 40, current_date)"
	)
}}
```

### Expected results

A fricitionless run

### Actual results

I get the following warning

```
Warning: the `dateadd` macro is now provided in dbt Core. It is no longer available in dbt_utils and backwards compatibility will be removed in a future version of the package. Use `dateadd` (no prefix) instead. The getaround_eu.snowflake_amortized_rates model triggered this warning.
```

### Screenshots and log output
![image](https://user-images.githubusercontent.com/21106392/201732201-166bfdb4-547c-4dd6-aa4f-ddeb4012a68f.png)

### System information
**The contents of your `packages.yml` file:**

```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.0
  - package: dbt-labs/audit_helper
    version: 0.5.0
  - package: dbt-labs/codegen
    version: 0.5.0
  - package: dbt-labs/dbt_external_tables
    version: 0.8.0
  - package: calogica/dbt_expectations
    version: [">=0.5.0", "<0.6.0"]
  - package: tnightengale/dbt_meta_testing
    version: 0.3.5
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

```
Core:
  - installed: 1.2.2
  - latest:    1.3.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.2.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Additional context

The model comes from a previously maintained by Gitlab package
https://gitlab.com/gitlab-data/snowflake_spend

### Are you interested in contributing the fix?

I wouldn't know where to start
