### ISSUE TITLE
Can't have multiple expression_is_true tests with the same expression but different condition

### ISSUE THREAD

**Issue by joshuataylor** [dbt-labs/dbt-utils#742]
### Describe the bug
When having a test like this:
```yaml
tests:
  - dbt_utils.expression_is_true:
      expression: "is not null"
      config:
        where: "something > 0"
  - dbt_utils.expression_is_true:
      expression: "is not null"
      config:
        where: "something_else_complicated > 2"
```

It throws an error as it builds the test name based off the expression. It is possible to move these into an OR, but sometimes it's easier to have two tests as the logic can be complicated sometimes.

### Steps to reproduce
Create two expression is true tests with the same expression.

### Expected results
It works. I think since the change to 1.0.0, it no longer uses the expression in the file name?

### Screenshots and log output
```
  Since these resources have the same name, dbt will be unable to find the correct resource
  when running tests.
  
  To fix this, change the name of one of these resources:
  - test.foo.dbt_utils_expression_is_true_bar_something__is_not_null.b9c184509b (models/staging/xx/yy.yml)
  - test.foo.dbt_utils_expression_is_true_bar_something__is_not_null.b9c184509b (models/staging/xx/yy.yml)
```

### System information
**The contents of your `packages.yml` file:**
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
1.3.1

### Additional context
This use to work, so it's technically a regression?

### Are you interested in contributing the fix?
Sure?
