### ISSUE TITLE
[Bug] Using combo schema names in generate_schema_name() causes union_relations to generate invalid SQL

### ISSUE THREAD

**Issue by jaredx435k2d0** [dbt-labs/dbt-utils#747]
### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: calogica/dbt_date
    version: 0.7.0

  - package: dbt-labs/dbt_utils
    version: 1.0.0

  # - package: dbt-labs/dbt_project_evaluator
  #   version: 0.2.0

  # - package: calogica/dbt_expectations
  #   version: 0.7.0

  - package: dbt-labs/codegen
    version: 0.9.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.0
  - latest:    1.3.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0 - Up to date!
```
