### ISSUE TITLE
Generic Test: Not Null if another column if not null

### ISSUE THREAD

**Issue by culpgrant** [dbt-labs/dbt-utils#780]
### Describe the feature
This is a little weird to explain but if you have two columns: column a and column b. Having a test to say if column a is null then column b should not be null.

This is especially helpful if you have a `case when statement` that you want to make sure is correct.

### Describe alternatives you've considered
I dont see this as a generic test already - I did implement this as a test within my project that I thought other people might benefit from.

### Additional context
Should be database agnostic.

### Who will this benefit?
Teams who want to use testing more.

### Are you interested in contributing this feature?
Yes! This would be my first contribution so a little guidance might be helpful

**Comment by joellabes** [comment]
Hey @culpgrant! This is already possible using out of the box functionality: 

```yaml
models:
  - name: my_model
    columns: 
      - name: column_b
        tests:
          - not_null:
              config: 
                where: column_a is null
```

Check out https://docs.getdbt.com/reference/resource-configs/where for more details; for now I'll close this but lmk if there's some context I'm missing
