### ISSUE TITLE
unique_combination_of_columns should be configurable for not failing with null values

### ISSUE THREAD

**Issue by The-Pavel** [dbt-labs/dbt-utils#784]
### Describe the feature
Currently `unique_combination_of_columns` test will always fail if `null` values in the columns that are tested result in non-unique combinations. 

For example, consider the `orders` table below:

| order_id | client_name | country |
|-------|-------------|---------|
| 1 | Company X   | US      |
| 2 | Company X   | UK      |
| 3 | Company Y   | _null_    |
| 4 | Company Y   | _null_    |

And the corresponding `schema.yml`:

```yml
models:
  - name: orders
    columns:
      - name: order_id
      - name: client_name
      - name: country
    tests:
      - dbt_utils.unique_combination_of_columns:
           combination_of_columns:
             - client_name
             - country
             
```

In the example above the `unique_combination_of_columns` test will **always** fail because of the last two rows. ❌

However, same way that the [uniqueness test should not be violated by null values in a unique key column](https://github.com/dbt-labs/dbt-core/issues/207), I think the same logic applies to a combination of multiple unique key columns - if a `not_null` test is needed, it should be added separately to relevant columns in `schema.yml`.

### Describe alternatives you've considered
- Creating a surrogate key - doesn't work, because there are cases when a column has null values, but unique combination only needs to be validated for existing values
- Adding `not_null` tests to specific columns - doesn't fit the use case

### What worked

I've adapted the [original source code of `unique_combination_of_columns` test](https://github.com/dbt-labs/dbt-utils/blob/main/macros/generic_tests/unique_combination_of_columns.sql) to write a custom test:

```jinja
{% test column_combination_is_unique_where_not_null(model, column_names) %}

with validation_errors as (
    select
        {{ column_names | join(', ') }}
    from {{ model }}
    WHERE
    {%- for column in column_names %}
      {{ "AND" if not loop.first }} {{ column }} IS NOT NULL
    {% endfor -%}
    group by {{ column_names | join(', ') }}
    having count(*) > 1
)

select *
from validation_errors

{% endtest %}
```

If there are reasons against having this as a default behaviour, I think having an optional argument like `count_nulls=true` to conditionally add/remove the `WHERE` clause would be great!

### Who will this benefit?
Anyone dealing with unique combination of columns, where null values are allowed.

### Are you interested in contributing this feature?
Yes! ✅

**Comment by joellabes** [comment]
Hmmm this is a very interesting point @The-Pavel! The link to the original Core issue way back when is a good callout. 

It certainly can't be the default behaviour, because that would result is a breaking change compared to what is shipping in version 1.x.y of the package, and we won't make any non-backwards-compatible breaking changes. 

Could you do it like this: 

```
models:
  - name: orders
    columns:
      - name: order_id
      - name: client_name
      - name: country
    tests:
      - dbt_utils.unique_combination_of_columns:
           combination_of_columns:
             - client_name
             - country
           config: 
             where: client_name is not null and country is not null
```

The `where` config would filter out the null-y ones. 

For now, given the workaround possible, I'm going to tentatively decline this one (but leave it open). If other folks also come across this and would find it useful, I'm definitely willing to reconsider, but the fact that it's been out in the world as-is for this long without issue makes me think that adding the extra complexity probably isn't worth it.
