### ISSUE TITLE
dbt_utils.get_column_values does not work when relation is used in source function

### ISSUE THREAD

**Issue by krati-sharma-ada** [dbt-labs/dbt-utils#809]
### Describe the bug

The `get_column_values` macro does not seem to work when relation is passed in source function when the relation clearly exists in redshift and running just the source function with same variables works fine. 

### Steps to reproduce

`{%- set table_results = dbt_utils.get_column_values(table=source('salesforce', 'fivetran_formula_model'), column='model', where="object = 'account'")  -%}`

Here's what I have in source.yml:

```
version: 2

sources:
  - name: salesforce # It would be best to keep this named salesforce
    schema: salesforce_5tran_new # Configure the salesforce_schema var from your dbt_project.yml (alternatively you can hard-code the schema here if only using one Salesforce connector)
    # Add the database where your Salesforce data resides if different from the target database. Eg. 'my_salesforce_database'. By default the target.database is used.
    tables:
      - name: fivetran_formula_model
        description: Used for the recommended Option 1 version of the formula solution.
      - name: account
        description: Salesforce account object fields
```

### Expected results

The column values for model column is returned from `salesforce_5tran_new.fivetran_formula_model` relation. 

### Actual results

```
  Compilation Error in model salesforce__account_view (models/example/salesforce__account_view.sql)
    'str object' has no attribute 'database'
```

### Screenshots and log output

![get_column_values_error](https://github.com/dbt-labs/dbt-utils/assets/127904510/aea8d6f2-22f7-401f-a70e-1165b992bf25)

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: fivetran/salesforce_formula_utils
    version: [">=0.8.0", "<0.9.0"] # we recommend using ranges to capture non-breaking changes automatically
  - package: dbt-labs/dbt_external_tables
    version: 0.8.5
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

```
Core:
  - installed: 1.5.1
  - latest:    1.5.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - redshift: 1.5.4 - Update available!
  - postgres: 1.5.1 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Additional context

```
        {%- if not relation_exists and default is none -%}

          {{ exceptions.raise_compiler_error("In get_column_values(): relation " ~ target_relation ~ " does not exist and no default value was provided.") }}
```

### Are you interested in contributing the fix?

I do not know what's causing the error. 

@fivetran-joemarkiewicz let me know if you think I should add any more details to describe the issue better.
