### ISSUE TITLE
dbt_utils.star ignores column names starting with '#' in dbt-databricks

### ISSUE THREAD

**Issue by derik-roby** [dbt-labs/dbt-utils#825]
### Describe the bug
The `dbt_utils.star()`  SQL generator function ignores the column names starting with '#' in dbt-databricks. In the generated comma-separated list of all fields, column names starting with '#' are ignored. 

### Steps to reproduce
* Create a table in databricks with column names starting with ***'#'***
```
CREATE TABLE raw.calendar_test (
	listing_id STRING,
	date STRING,
	available STRING,
	price STRING,
	adjusted_price STRING,
	minimum_nights STRING,
	maximum_nights STRING,
    `#testColumn` STRING,
    `#test2Column` STRING
) 
```
* Updated the *sources.yml* file for including new table.
* Write a dbt model (*stg_star_test.sql*) for this table using the `dbt_utils.start` function.
```
{{
config(
schema='staging'
)
}}
WITH stg_calendar_test AS (
    SELECT {{ dbt_utils.star(source('dbt_demo', 'calendar_test'),prefix='test_') }} FROM {{ source('dbt_demo', 'calendar_test') }}
)
SELECT
    *
FROM
    stg_calendar_test
```

### Expected results
All column in calendar_test table should be included in the stg_star_test models' materialization. 

### Actual results
Column names starting with '#' are omitted. (From the example, #testColumn and #test2Column). The compiled models also does not contain these columns.
![image](https://github.com/dbt-labs/dbt-utils/assets/122028333/e1db8dd3-31dd-4937-92f8-0dfbc6365984)

### System information
```
packages:
- package: dbt-labs/dbt_utils
  version: [">=1.1.0", "<1.2.0"]
- package: emilyriederer/dbtplyr
  version: [">=0.3.0", "<0.4.0"]
- package: calogica/dbt_expectations
  version: [">=0.8.0", "<0.9.0"]
- package: dbt-labs/dbt_project_evaluator
  version: [">=0.5.0", "<0.6.0"]
```

**Which database are you using dbt with?**
- [ ] databricks

Columns with '#' are generated for dbt-postgres. 

**The output of `dbt --version`:**
```
Core:
  - installed: 1.6.0
  - latest:    1.6.0 - Up to date!

Plugins:
  - databricks: 1.6.1 - Up to date!
  - spark:      1.6.0 - Up to date!

```
