### ISSUE TITLE
Add optional `exclude_columns` to the `equality` test

### ISSUE THREAD

**Issue by seub** [dbt-labs/dbt-utils#828]
### Describe the feature

It'd be nice to have an optional `exclude_columns` in the `equality` test, similar to `compare_columns`:

```yaml
    tests:
      - dbt_utils.equality:
          compare_model: ref('other_table_name')
          exclude_columns:
            - third_column
            - fourth_column
```

Such columns would be ignored when comparing the two tables.

### Describe alternatives you've considered

1. Rewrite the test in our projects
2. Somehow leverage `compare_relations` from [dbt-audit-helper](https://github.com/dbt-labs/dbt-audit-helper/blob/main/macros/compare_relations.sql)

I don't think either solution is great compared to adding the feature here.

### Additional context / Who will this benefit?

As an example, here's why my team would like this. We leverage the `equality` test from dbt-utils to implement unit tests. However, we need to exclude the "processing timestamp" column, as it cannot be predicted for the "expected output" model.

### Are you interested in contributing this feature?

Yep! In fact, I wrote the PR ([#829 ](https://github.com/dbt-labs/dbt-utils/pull/829)) before the issue, because I'd forgotten that all PRs must be associated with an issue, oops.
