### ISSUE TITLE
Test Descriptions

### ISSUE THREAD

**Issue by madarez** [dbt-labs/dbt-utils#837]
### Describe the bug
I'm trying to add descriptions to my tests, but whatever I try it won't add descriptions there when I look at it in the `dbt doc`, and I suppose it's not supported. Can we enable descriptions?

### Steps to reproduce
1. create a test file
2. set description
  - in a `schema.yml` or inside the file next to or within configs --> see [Screenshots](#screenshots)
3. run `dbt doc` generate and serve
4. select the test from the navigator
5. see the description

### Expected results
N/A

### Actual results
No description is written there for tests

### Screenshots
Here's the yml file I tried settting descriptions for that sits next to the test SQL file:
<img width="310" alt="Screen Shot 2023-09-20 at 5 02 24 PM" src="https://github.com/dbt-labs/dbt-utils/assets/31979020/18a226df-ef42-4b8b-bf21-a2a6ffa9ca4f">

Here's my attempt with setting it within the test SQL file:
<img width="1162" alt="Screen Shot 2023-09-20 at 4 59 52 PM" src="https://github.com/dbt-labs/dbt-utils/assets/31979020/7b2d3b1c-35e2-4387-9c4e-f42bf25bcbac">

### System information
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - git: "https://github.com/EqualExperts/dbt-unit-testing"
    revision: v0.2.6
  - package: calogica/dbt_expectations
    version: [">=0.8.0", "<0.9.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.1
  - latest:    1.6.3 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.4.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Additional context
I suspect it is not be supported today.

### Are you interested in contributing the fix?
Sorry, I can't
