### ISSUE TITLE
Version Conflict with DBT_Utils

### ISSUE THREAD

**Issue by edwrand** [dbt-labs/dbt-utils#840]
# Describe the bug

### My packages.yml is as follows and runs correctly when using dbt deps:

```
packages:
  - package: dbt-labs/audit_helper
    version: 0.5.0

  - package: dbt-labs/codegen
    version: 0.7.0

  - package: Snowflake-Labs/dbt_constraints
    version: [">=0.3.0", "<0.4.0"]
    
  - package: calogica/dbt_date
    version: [">=0.5.0", "<0.6.0"]

  - package: calogica/dbt_expectations
    version: [">=0.5.0", "<0.6.0"]

  - package: dbt-labs/spark_utils
    version: [">=0.3.0", "<0.4.0"]

  - package: data-mie/dbt_profiler
    version: [">=0.3.2", "<0.4.0"]

  - package: re-data/re_data
    version: [">=0.8.0", "<0.9.0"]

  - package: dbt-labs/dbt_utils
    version: [">=0.7.0", "<1.1.1"]
```

### Next, I want to add DBT_project_evlauator so I add the code below at the end of packages.yml similar to adding any other package.

```
 - package: dbt-labs/dbt_project_evaluator
    version: 0.8.0
```

# Steps to reproduce

### Put the same packages in your packages.yml and run DBT deps to reproduce.

# Expected results

### Actual results

# I get an error that says 
`DependencyException
Version error for package dbt-labs/dbt_utils: Could not find a satisfactory version from options: ['>=0.7.0', '<1.1.1', '>=0.8.0', '<0.9.0', '>=0.8.0', '<0.9.0', '>=0.8.0', '<0.9.0', '>=0.7.0', '<0.9.0', '>=1.0.0', '<2.0.0']
DependencyException`

# Screenshots and log output

If applicable, add screenshots or log output to help explain your problem.

### Runs successfully without the added package

<img width="1728" alt="Screenshot 2023-09-26 at 3 56 42 PM" src="https://github.com/dbt-labs/dbt-utils/assets/78825417/cc32b37b-e8b9-4c56-9122-3e9cd8033338">

### Breaks with this error message when I add the dbt_project_evaluator package:

<img width="1728" alt="Screenshot 2023-09-26 at 3 57 46 PM" src="https://github.com/dbt-labs/dbt-utils/assets/78825417/7a626787-67a8-402c-8ab2-8a2ba1c31627">

# System information
**The contents of your `packages.yml` file:**

```
packages:
  - package: dbt-labs/audit_helper
    version: 0.5.0

  - package: dbt-labs/codegen
    version: 0.7.0

  - package: Snowflake-Labs/dbt_constraints
    version: [">=0.3.0", "<0.4.0"]
    
  - package: calogica/dbt_date
    version: [">=0.5.0", "<0.6.0"]

  - package: calogica/dbt_expectations
    version: [">=0.5.0", "<0.6.0"]

  - package: dbt-labs/spark_utils
    version: [">=0.3.0", "<0.4.0"]

  - package: data-mie/dbt_profiler
    version: [">=0.3.2", "<0.4.0"]

  - package: re-data/re_data
    version: [">=0.8.0", "<0.9.0"]

  - package: dbt-labs/dbt_utils
    version: [">=0.7.0", "<1.1.1"]

  - package: dbt-labs/dbt_project_evaluator
    version: 0.8.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

<img width="1419" alt="Screenshot 2023-09-26 at 4 00 49 PM" src="https://github.com/dbt-labs/dbt-utils/assets/78825417/a8634399-924c-42d1-a4e3-d65177c38e25">
