### ISSUE TITLE
Mutually exclusive ranges support multiple partition by arguments

### ISSUE THREAD

**Issue by bornabare** [dbt-labs/dbt-utils#858]
### Describe the feature

Mutually exclusive ranges test by documentation supports optional partition_by argument. 
It would be great if it can support multiple partition by arguments in cases where users might not want to generate surrogate key. 

This test by default already pretty much could accept multiple partition by arguments, separated by comma.

What is not stated, but could be, is that this part of the clause could easily get multiple column names as input separated by comma. 

### Describe how to reproduce issue/feature

This is an example of yml file with test part:
```
version: 2

sources:
  - name: xy
    database: xz
    schema: zy
    tables: 
      - name: time_entry_tag
        tests:
        - dbt_utils.mutually_exclusive_ranges:
            lower_bound_column: valid_from
            upper_bound_column: valid_to
            partition_by: time_entry_id, tag_name, tag_type
            gaps: required
            zero_length_range_allowed: true
```

Compilation successfully produces valid sql code that produces valid error failures in validation error.

The only change apart from updating documentation would be removing aliasing in window_function cte. 

```
with window_functions as (

    select
        
        time_entry_id, tag_name, tag_type as partition_by_col,
        
        valid_from as lower_bound,
        valid_to as upper_bound,
...
```

### Are you interested in contributing this feature?

I am interested to rephrase the documentation and update macro aliasing.
