### ISSUE TITLE
total equals sum

### ISSUE THREAD

**Issue by kylemcnair** [dbt-labs/dbt-utils#867]
### Describe the feature
My org has a series of what we call "invariant" tests, a subset of which require that total amounts match the sum of their parts.  It's a simple test, but has been useful for flagging potential data issues with revenue models. 

Example test in plain English: `"today's ARR = yesterday's ARR + net new ARR"`

```
 - total_equals_sum:
        total: c
        parts: [a, b]
        threshold: 0 [optional argument]
```
The threshold parameter is a way to allow for _some_ absolute difference in the comparisons (to sidestep errors related to rounding or levels of precision).

I recognize this might be too narrow a test, and might bloat this package, but figured I'd open an issue in case others might find it useful. `expression is true` absolutely covers this use case in a more flexible way, but can at times be _too_ generic. My feelings won't be hurt if this is passed on, just throwing it out 😃 

### Describe alternatives you've considered
The `equality` util sorta does this, but across models. 

`expression_is_true` can accomplish this, but I found it to not be as explicit.
```
      - dbt_utils.expression_is_true:
          expression:
            'abs(eop_arr -
              (prior_day_eop_arr
              + net_new_arr)
            ) <= 1'
```
vs
```
      - total_equals_sum:
          total: eop_arr
          parts: [prior_day_eop_arr, net_new_arr]
          threshold: 1
```
Could also write a custom test for this.

Unsure if there's anything else out of the box that handles this use case. I thought there might be, but didn't find anything.

### Additional context
n/a

### Who will this benefit?
I'd view this as a solution for projects that have really run with `expression_is_true`, and serves to simplify common comparisons in a very legible and explicit manner. 

### Are you interested in contributing this feature?

I'd be happy to contribute if others find this useful.
