### ISSUE TITLE
ENHANCEMENT: Update `fail_calc` for `not_null_proportion` to allow for custom `error_if` and `warn_if` configs

### ISSUE THREAD

**Issue by garfieldthesam** [dbt-labs/dbt-utils#874]
### Describe the feature
My testing strategy revolves around having warn and error thresholds for most tests. I would like to configure a `not_null_proportion` test like this:
```
      - name: test_name
        test_name: dbt_utils.not_null_proportion
        column_name: "some_column"
        where: some_where_clause
        config:
          severity: warn
          warn_if: <= 0.98
          error_if: <= 0.95
```

However, when I run a test configured like this, the compiled code sent to my Databricks SQL Warehouse is like this:
```
select
  count(*) as failures,
  count(*) <= 0.98 as should_warn,
  count(*) <= 0.95 as should_error
from
  (
    with validation as (
      select
        sum(
          case
            when some_column is null then 0
            else 1
          end
        ) / cast(count(*) as numeric) as not_null_proportion
      from
        some_table
    ),
    validation_errors as (
      select
        not_null_proportion
      from
        validation
      where
        not_null_proportion < 1.00000000001
        or not_null_proportion > 1
    )
    select
      *
    from
      validation_errors
  ) dbt_internal_test
```

This test will never fire a warning or an error because count(*) always evaluates to 1 and therefore neither of the below lines in the select statement will be true:
```
  count(*) <= 0.98 as should_warn,
  count(*) <= 0.95 as should_error
```

This can be changed by using a different `fail_calc` configuration in the `not_null_proportion` test eg: `{{ config(fail_calc = 'coalesce(not_null_proportion, 0)') }}` 

### Describe alternatives you've considered

N/A

### Additional context
N/A

### Who will this benefit?

Anyone who wants to be able to configure separate thresholds for triggering a warning from a `not_null_proportion` test from an error. 

This is useful for anyone using `dbt_utils` with a package like [elementary](https://github.com/elementary-data/elementary) to track `warn` results over time for triage and informational purposes.

### Are you interested in contributing this feature?

Yes, possibly, though I'd probably need a bit of help setting up an integration test
