### ISSUE TITLE
add description tag to test definition

### ISSUE THREAD

**Issue by maares** [dbt-labs/dbt-utils#882]
### Describe the feature
Would like to add description to tests.

```
tests:
  - dbt_utils.expression_is_true:
      name: test_name
      description: “test_description"
      expression: '= X'
      config:
        where: “X= N"
```

### Describe alternatives you've considered
Using name as declarative as possible of whats being tested is not enough.

### Additional context
As the package can store test results in database, table description would be nice.

### Who will this benefit?
Better understanding for any test being executed. Normally 6 months after deployment no dev-team members remembers the why. Having a more declarative way of the intent on test will help maintainability in the long run

### Are you interested in contributing this feature?
Have never contributed, and not even know where to start, if some guidance is given then definitely.
