### ISSUE TITLE
Unable to install dbt-utils 

### ISSUE THREAD

**Issue by pranjalbhatt** [dbt-labs/dbt-utils#950]
### Describe the bug
I am unable to install `dbt_utils` package on my hardware. Multiple attempts to install the package, but spits out an error.

**Environment** 

```
- OS: Windows 10
- Python: 3.12.3
- dbt-core: 1.8.1
```
Upon execution, returns error message as follows:
```
ConnectionError: External connection exception occurred: not a gzip file
``` 

### Steps to reproduce
1. Add packages to `packages.yml` file
2. Run `dbt deps`
3. Observe error `External connection exception occurred: not a gzip file`

### Expected results
`dbt deps` command should install the package successfully. 

### Actual results
Relevant log ouput:
```
20:44:18  Running with dbt=1.8.1
20:44:20  Updating lock file in file path: C:\Users\PBhatt\OneDrive - CBRE, Inc\Documents\SDP GIT Repo\...\package-lock.yml
20:44:20  Installing dbt-labs/dbt_utils
20:44:28  Encountered an error:
External connection exception occurred: not a gzip file
``` 

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: calogica/dbt_date
    version: 0.10.1
  - package: calogica/dbt_expectations
    version: 0.10.4
  - package: brooklyn-data/dbt_artifacts
    version: 2.6.4
  - package: dbt-labs/dbt_utils
    version: 1.3.0
```

**Which database are you using dbt with?**
- [ ]  snowflake

**The output of `dbt --version`:**
```
Core:
  - installed: 1.8.1
 ```

**Comment by dbeatty10** [comment]
What if you just try only including the `dbt_date` package in your `packages.yml`? Does that work?

```yaml
packages:
  - package: calogica/dbt_date
    version: 0.10.1
```

I'd be curious if it is affecting all packages or just `dbt_utils`. e.g., I'd be curious if this works for you or not also:

```yaml
packages:
  - package: calogica/dbt_date
    version: 0.10.1
  - package: calogica/dbt_expectations
    version: 0.10.4
  - package: brooklyn-data/dbt_artifacts
    version: 2.6.4
```
