### ISSUE TITLE
union_relations guesses data types incorrectly so database fails

### ISSUE THREAD

**Issue by EugenioGastelumGBR** [dbt-labs/dbt-utils#957]
### System information
**The contents of your `packages.yml` file:**
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - package: calogica/dbt_expectations
    version: [">=0.10.0", "<0.11.0"]

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - package: calogica/dbt_expectations
    version: [">=0.10.0", "<0.11.0"]
```
