### ISSUE TITLE
`dbt_utils.get_url_parameter` will incorrectly match fields if they end with the field

### ISSUE THREAD

**Issue by jasonlanderson** [dbt-labs/dbt-utils#980]
### Steps to reproduce
When using `dbt_utils.get_url_parameter` it will incorrectly match on short 
For example when doing the following and the url field values is `http://www.test.com?msg=myvalue` it will incorrectly return "myvalue".

`dbt_utils.get_url_parameter(field='url', url_parameter='g')`

### Expected results

In the above scenario, it should only exact match the URL parameter and return null

### Actual results

It matches and returns "myvalue"

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: calogica/dbt_expectations
    version: [">=0.9.0", "<0.10.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [X] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.8.2
```

### Additional context
I believe it's this implementation here https://github.com/dbt-labs/dbt-utils/blob/main/macros/web/get_url_parameter.sql#L5

### Are you interested in contributing the fix?
I've switched to using the following but not sure this solution is entirely correct either

`nullif(regexp_substr({{ field }}, '[?&]{{ url_parameter }}=([^&]+)', 1, 1, 'e'), '')`
