### ISSUE TITLE
[Docs] Passing the `unique` data test a concatenation of column names

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-utils#994]
### Describe the docs update

[This](https://github.com/dbt-labs/dbt-utils?tab=readme-ov-file#unique_combination_of_columns-source) example will need updating after https://github.com/dbt-labs/docs.getdbt.com/pull/6961.

> passing the unique test a concatenation of the columns (as discussed [here](https://docs.getdbt.com/docs/building-a-dbt-project/testing-and-documentation/testing/#testing-expressions)).

Two things in particular:
1. The link is already out-of-date
2. Even if we update the link, it will no longer include the relevant content after https://github.com/dbt-labs/docs.getdbt.com/pull/6961 is merged

So we should either:
1. Remove that line entirely, or
2. Add an example like the following:
    ```yaml
        tests:
          - unique:
              column_name: "country_code || '-' || order_id"
    ```
